require("general")
-- require("config.gitsigns")
require("plugins")
require("vim")
require("plug_config.cmp")
require("plug_config.colorscheme")
require("plug_config.lsp")
require("plug_config.neotree")
require("plug_config.test")
require("plug_config.treesitter")
require("plug_config.whichkey")
